version: '3'
services:
  nginx:
    build: ./nginx/
    restart: always
    ports:
      - "8080:80"
  node:
    build: ./node/
    restart: always
    volumes: 
      - ../node:/usr/node
    environment: 
      - APPPORT:8888
  redis:
    build: ./redis/
  postgres:
    build: ./postgres/
    env_file: 
      - postgres-env.env

