version: '3'
services:
  nginx:
    build: ./nginx/
    ports:
      - "8080:80"
  node:
    build: ./node/
    volumes: 
      - ../node:/usr/node
  redis:
    build: ./redis/
  postgres:
    build: ./postgres/
    env_file: 
      - postgres-env.env

